age: 25
name: Bruno
address: Paris
server:
  address: 192.168.2.10 # Use your local ip
spring:
  application:
    name: demo-consul
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      config:
        format: yaml